/**
 * Writes `dist/_headers` after a build.
 *
 * The Content-Security-Policy names a hash for every inline script that
 * actually shipped. Astro inlines its small scripts and their contents change
 * whenever the source does, so a hand-maintained list in netlify.toml would go
 * stale on the next commit — and a stale script hash does not fail the build,
 * it fails silently in the browser for visitors only. Generating the header
 * from `dist` is the only version of this that stays true.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

const walk = async (dir) => {
	const out = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...(await walk(path)));
		else if (entry.name.endsWith('.html')) out.push(path);
	}
	return out;
};

const pages = await walk(DIST);
if (pages.length === 0) throw new Error('no pages in dist — run astro build first');

// Every inline <script> that shipped. `src=` scripts are covered by 'self'.
const hashes = new Set();
for (const page of pages) {
	const html = await readFile(page, 'utf8');
	for (const [, body] of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
}

// The project's own Supabase origin, so the policy names one host rather than
// every project on supabase.co. Falls back to the wildcard when the variable is
// not set, which is the case for a local build.
const supabase = process.env.PUBLIC_SUPABASE_URL
	? new URL(process.env.PUBLIC_SUPABASE_URL).origin
	: 'https://*.supabase.co';

const csp = [
	`default-src 'self'`,
	`script-src 'self' ${[...hashes].sort().join(' ')}`,
	// Astro extracts component styles to files, but 35-odd `style=` attributes
	// remain in the markup. style-src-attr would be tighter; it is not old
	// enough to rely on alone, and losing it means losing the layout.
	`style-src 'self' 'unsafe-inline'`,
	`img-src 'self' data:`,
	`font-src 'self'`,
	// api.postalpincode.in resolves an Indian PIN to its district.
	`connect-src 'self' ${supabase} https://api.postalpincode.in`,
	`form-action 'self'`,
	`frame-ancestors 'self'`,
	`base-uri 'self'`,
	`object-src 'none'`,
	`upgrade-insecure-requests`,
].join('; ');

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# Regenerated on every build so the script hashes match what shipped.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: SAMEORIGIN
  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
`;

await writeFile(join(DIST, '_headers'), headers);
console.log(
	`_headers written — ${hashes.size} inline script hashes across ${pages.length} pages`,
);
