/**
 * Writes `dist/_headers` after a build.
 *
 * Netlify and Cloudflare Pages read the same `_headers` format, which is why
 * moving between them costs nothing here: the policy that took the longest to
 * get right is the part that did not have to change.
 *
 * The Content-Security-Policy names a hash for every inline script that
 * actually shipped. Astro inlines its small scripts and their contents change
 * whenever the source does, so a hand-maintained list in netlify.toml would go
 * stale on the next commit — and a stale script hash does not fail the build,
 * it fails silently in the browser for visitors only. Generating the header
 * from `dist` is the only version of this that stays true.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

const walk = async (dir) => {
	const out = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...(await walk(path)));
		else if (entry.name.endsWith('.html')) out.push(path);
	}
	return out;
};

const pages = await walk(DIST);
if (pages.length === 0) throw new Error('no pages in dist — run astro build first');

// Every inline <script> that shipped. `src=` scripts are covered by 'self'.
const hashes = new Set();
for (const page of pages) {
	const html = await readFile(page, 'utf8');
	for (const [, body] of html.matchAll(
		/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g,
	)) {
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
}

// The project's own Supabase origin, so the policy names one host rather than
// every project on supabase.co.
//
// Astro loads `.env` for the site it builds, but this runs as a separate node
// process afterwards and does not inherit it. Read the file directly when the
// variable is not already in the environment: otherwise a local build quietly
// widens the policy to every project on supabase.co, which still works and so
// is never noticed.
const fromEnvFile = async () => {
	try {
		const text = await readFile(new URL('../.env', import.meta.url), 'utf8');
		return text
			.match(/^\s*PUBLIC_SUPABASE_URL\s*=\s*(.+)$/m)?.[1]
			.trim()
			.replace(/^["']|["']$/g, '');
	} catch {
		return undefined;
	}
};

const supabaseUrl = process.env.PUBLIC_SUPABASE_URL || (await fromEnvFile());
const supabase = supabaseUrl ? new URL(supabaseUrl).origin : 'https://*.supabase.co';

/**
 * Razorpay Checkout.
 *
 * It is a hosted window: a script we load, an iframe it draws, and its own
 * telemetry and API origins. The alternative to naming these is a payment
 * button that silently does nothing, because a blocked script raises no error
 * a visitor can see. They are listed here rather than widened with a wildcard
 * so that adding a second gateway is a visible decision.
 *
 * `frame-src` is what the checkout window itself needs; UPI intent links leave
 * the browser entirely and are not a frame.
 */
const RAZORPAY = {
	// checkout.razorpay.com is the window itself; cdn.razorpay.com carries the
	// fraud-detection bundle it loads, which is part of the payment rather than
	// an extra. Blocking it leaves the checkout working and its risk checks not.
	scripts: ['https://checkout.razorpay.com', 'https://cdn.razorpay.com'],
	frames: ['https://api.razorpay.com', 'https://checkout.razorpay.com'],
	connect: [
		'https://api.razorpay.com',
		'https://lumberjack.razorpay.com',
		'https://lumberjack-cx.razorpay.com',
	],
	images: ['https://cdn.razorpay.com', 'https://*.rzp.io'],
};

const csp = [
	`default-src 'self'`,
	`script-src 'self' ${RAZORPAY.scripts.join(' ')} ${[...hashes].sort().join(' ')}`,
	// Astro extracts component styles to files, but 35-odd `style=` attributes
	// remain in the markup. style-src-attr would be tighter; it is not old
	// enough to rely on alone, and losing it means losing the layout.
	`style-src 'self' 'unsafe-inline'`,
	`img-src 'self' data: ${RAZORPAY.images.join(' ')}`,
	`font-src 'self'`,
	// api.postalpincode.in resolves an Indian PIN to its district.
	`connect-src 'self' ${supabase} https://api.postalpincode.in ${RAZORPAY.connect.join(' ')}`,
	`form-action 'self'`,
	`frame-src ${RAZORPAY.frames.join(' ')}`,
	// Nothing frames this site, including this site. Denying it outright closes
	// clickjacking rather than narrowing it.
	`frame-ancestors 'none'`,
	`base-uri 'self'`,
	`object-src 'none'`,
	// No plugins, no workers, no manifests: nothing here uses them, and a
	// directive that is absent falls back to default-src rather than to nothing.
	`worker-src 'none'`,
	`manifest-src 'self'`,
	`upgrade-insecure-requests`,
].join('; ');

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# Regenerated on every build so the script hashes match what shipped.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  # DENY rather than SAMEORIGIN, to match frame-ancestors 'none' for the older
  # browsers that read this header instead of the policy.
  X-Frame-Options: DENY
  # Every powerful feature the platform offers, switched off. The site asks for
  # none of them, and a feature that is never requested cannot be abused by
  # anything that finds its way onto the page.
  Permissions-Policy: accelerometer=(), autoplay=(), browsing-topics=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), xr-spatial-tracking=()
  # Severs the window.opener link, so a page opened from here cannot reach back
  # into it, and puts this document in its own browsing-context group.
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Caching. These lived in netlify.toml until the site moved to Cloudflare
# Pages, which reads this file and not that one. They belong here anyway: one
# file, generated, saying everything the CDN needs to know.

# Fingerprinted. The filename changes when the contents do, so it can be held
# forever and never revalidated.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The plates and the brand marks are not fingerprinted and are most of the
# page weight, so they are held hard but still checked.
/plates/*
  Cache-Control: public, max-age=604800, must-revalidate

/brand/*
  Cache-Control: public, max-age=604800, must-revalidate

/shop/*
  Cache-Control: public, max-age=604800, must-revalidate
`;

await writeFile(join(DIST, '_headers'), headers);
console.log(
	`_headers written — ${hashes.size} inline script hashes across ${pages.length} pages`,
);
