/**
 * Writes `dist/_headers` after a build.
 *
 * Netlify and Cloudflare Pages read the same `_headers` format, which is why
 * moving between them costs nothing here: the policy that took the longest to
 * get right is the part that did not have to change.
 *
 * The Content-Security-Policy names a hash for every inline script that
 * actually shipped. Astro inlines its small scripts and their contents change
 * whenever the source does, so a hand-maintained list in netlify.toml would go
 * stale on the next commit — and a stale script hash does not fail the build,
 * it fails silently in the browser for visitors only. Generating the header
 * from `dist` is the only version of this that stays true.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

const walk = async (dir) => {
	const out = [];
	for (const entry of await readdir(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...(await walk(path)));
		else if (entry.name.endsWith('.html')) out.push(path);
	}
	return out;
};

const pages = await walk(DIST);
if (pages.length === 0) throw new Error('no pages in dist — run astro build first');

// Every inline <script> that shipped. `src=` scripts are covered by 'self'.
const hashes = new Set();
for (const page of pages) {
	const html = await readFile(page, 'utf8');
	for (const [, body] of html.matchAll(
		/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g,
	)) {
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
}

// The project's own Supabase origin, so the policy names one host rather than
// every project on supabase.co. Falls back to the wildcard when the variable is
// not set, which is the case for a local build.
const supabase = process.env.PUBLIC_SUPABASE_URL
	? new URL(process.env.PUBLIC_SUPABASE_URL).origin
	: 'https://*.supabase.co';

const csp = [
	`default-src 'self'`,
	`script-src 'self' ${[...hashes].sort().join(' ')}`,
	// Astro extracts component styles to files, but 35-odd `style=` attributes
	// remain in the markup. style-src-attr would be tighter; it is not old
	// enough to rely on alone, and losing it means losing the layout.
	`style-src 'self' 'unsafe-inline'`,
	`img-src 'self' data:`,
	`font-src 'self'`,
	// api.postalpincode.in resolves an Indian PIN to its district.
	`connect-src 'self' ${supabase} https://api.postalpincode.in`,
	`form-action 'self'`,
	// Nothing frames this site, including this site. Denying it outright closes
	// clickjacking rather than narrowing it.
	`frame-ancestors 'none'`,
	`base-uri 'self'`,
	`object-src 'none'`,
	// No plugins, no workers, no manifests: nothing here uses them, and a
	// directive that is absent falls back to default-src rather than to nothing.
	`worker-src 'none'`,
	`manifest-src 'self'`,
	`upgrade-insecure-requests`,
].join('; ');

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# Regenerated on every build so the script hashes match what shipped.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  # DENY rather than SAMEORIGIN, to match frame-ancestors 'none' for the older
  # browsers that read this header instead of the policy.
  X-Frame-Options: DENY
  # Every powerful feature the platform offers, switched off. The site asks for
  # none of them, and a feature that is never requested cannot be abused by
  # anything that finds its way onto the page.
  Permissions-Policy: accelerometer=(), autoplay=(), browsing-topics=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), publickey-credentials-get=(), screen-wake-lock=(), serial=(), usb=(), xr-spatial-tracking=()
  # Severs the window.opener link, so a page opened from here cannot reach back
  # into it, and puts this document in its own browsing-context group.
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Caching. These lived in netlify.toml until the site moved to Cloudflare
# Pages, which reads this file and not that one. They belong here anyway: one
# file, generated, saying everything the CDN needs to know.

# Fingerprinted. The filename changes when the contents do, so it can be held
# forever and never revalidated.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The plates and the brand marks are not fingerprinted and are most of the
# page weight, so they are held hard but still checked.
/plates/*
  Cache-Control: public, max-age=604800, must-revalidate

/brand/*
  Cache-Control: public, max-age=604800, must-revalidate

/shop/*
  Cache-Control: public, max-age=604800, must-revalidate
`;

await writeFile(join(DIST, '_headers'), headers);
console.log(
	`_headers written — ${hashes.size} inline script hashes across ${pages.length} pages`,
);
